---
- hosts: localhost

  environment:
    K8S_AUTH_CONTEXT: "{{ k8s_context }}"

  tasks:
   - name: Configure cert-manager
     ansible.builtin.include_role:
       name: cert-manager
     tags:
       - cert-manager
       - cert-manager-destroy

   - name: Configure telegram-bots
     ansible.builtin.include_role:
       name: telegram-bots
     tags:
       - telegram-bots
       - telegram-bots-destroy

   - name: Configure argo
     ansible.builtin.include_role:
       name: argo
     tags:
       - argo
       - argo-destroy
       - argo-cd
       - argo-cd-destroy
       - argo-events
       - argo-events-destroy
       - argo-workflows
       - argo-workflows-destroy

   - name: Configure tektonci
     ansible.builtin.include_role:
       name: tektonci
     tags:
       - tektonci
       - tektonci-destroy

   - name: Configure monitoring
     ansible.builtin.include_role:
       name: monitoring
     tags:
       - monitoring
       - monitoring-destroy
