---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'telegram-bot-aemet'
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: k3s-oracle
    namespace: telegram-bots
  project: default
  source:
    repoURL: 'https://gitlab.com/portfolio7771842/telegram-bot-aemet.git'
    path: kustomize
    targetRevision: HEAD
