apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-aemet-repo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.com/portfolio7771842/telegram-bot-aemet.git
