apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tekton-dashboard
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`tekton-dashboard.testing.com`)
      priority: 10
      services:
        - name: tekton-dashboard
          port: 9097
  tls: {}
